### ISSUE TITLE
Only 1 saved flash archive entry can be deleted after each boot

### ISSUE THREAD

**Issue by gierdo** [embeddedprojects/usbprog5#1]
After connecting the usbprog5 and connecting to it, only 1 entry of the flash archive can be deleted.
Trying to delet additional entries of the archive fails without error message.

Steps to reproduce:
- Connect usbprog5
- Open browser, point to 10.0.0.1
- Delete entry of flash archive
- Press "delete" button of second entry of flash archive

Result: Nothing happens.
Expected result: Second entry of flash archive is deleted.

Software version: 0.8.1

**Comment by gierdo** [comment]
server.py crashes after deleting the file

root@usbprog5:~# ./server.py 
starting up on  port 8888
('0.0.0.0', 8888)
/bin/rm: cannot remove `/tmp/gdb_runs': No such file or directory
waiting for a connection
connection from ('127.0.0.1', 38368)
decode
Traceback (most recent call last):
  File "./server.py", line 992, in <module>
    code=processor(code,connection)
  File "./server.py", line 201, in processor
    if code['v']>=1:
TypeError: 'NoneType' object is unsubscriptable
root@usbprog5:~#

**Comment by gierdo** [comment]
This issue is fixed with the update built from HEAD with the two pull requests applied.
The server crash is fixed but can only be run with fixing two minor syntax errors.

**Comment by embeddedprojects** [comment]
thank you - we forget to disable our debug mode - we try to find a better solution
