### ISSUE TITLE
Static MacAddr

### ISSUE THREAD

**Issue by hellow554** [embeddedprojects/usbprog5#4]
I don't know why, but the usbprog5 does not have a static mac address, which is not nice :( 
One solution would be to generate a random one at the first bootup and keep it forever.

If that's not possible (e.g. for some license reasons), you could write a section inside of the pdf that will explain how to set a fixed mac address.

**Comment by JasonBeard** [comment]
Hello punkkeks your issue is noted and we will work on it.
